# Generated by Django 4.1.1 on 2022-09-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese Nombre', max_length=30, verbose_name='Nombre')),
                ('apelllido', models.CharField(help_text='Ingrese Apellido', max_length=30, verbose_name='Apellido')),
                ('telefono', models.BigIntegerField(blank=True, help_text='Ingrese Número de Teléfono', null=True, verbose_name='Teléfono')),
                ('dpiSecre', models.CharField(help_text='Ingrese DPI', max_length=20, verbose_name='DPI de Secretaria')),
                ('direccion', models.CharField(help_text='Ingrese Dirección', max_length=50, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'db_table': 'secretaria',
            },
        ),
    ]
