# Generated by Django 4.1.1 on 2022-10-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secretaria', '0002_alter_secretaria_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secretaria',
            old_name='apelllido',
            new_name='apellido',
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='telefono',
            field=models.CharField(help_text='Ingrese Número de Teléfono', max_length=15, verbose_name='Teléfono'),
        ),
    ]
