# Generated by Django 4.1.1 on 2022-10-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consulta', '0008_alter_consulta_idcliente'),
        ('Recordatorio', '0004_alter_recordatorio_motivo_alter_recordatorio_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorio',
            name='finalizado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='M', help_text='Seleccione si esta finalizado o no', max_length=1, verbose_name='Finalizado'),
        ),
        migrations.AlterField(
            model_name='recordatorio',
            name='idConsulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consulta.consulta', verbose_name='Consulta'),
        ),
    ]
