# Generated by Django 4.1.1 on 2022-10-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recordatorio', '0006_alter_recordatorio_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordatorio',
            name='fechaRecordatorio',
        ),
        migrations.RemoveField(
            model_name='recordatorio',
            name='finalizado',
        ),
        migrations.RemoveField(
            model_name='recordatorio',
            name='horaRecordatorio',
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='estado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No'), ('R', 'Revisión')], default='M', help_text='Seleccione si esta finalizado o en revisón', max_length=1, verbose_name='Finalizado'),
        ),
    ]
