# Generated by Django 4.1.1 on 2022-10-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recordatorio', '0007_remove_recordatorio_fecharecordatorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorio',
            name='estado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No'), ('R', 'Revisión')], default='M', help_text='Seleccione si esta finalizado o en revisón', max_length=1, verbose_name='Estado'),
        ),
    ]
