# Generated by Django 4.1.1 on 2022-10-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recordatorio', '0008_alter_recordatorio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorio',
            name='estado',
            field=models.CharField(choices=[('Y', 'Si esta finalizado'), ('S', 'Sin completar'), ('R', 'Revisión')], default='M', help_text='Seleccione si esta finalizado, en revisón, sin completar', max_length=1, verbose_name='Estado'),
        ),
    ]
