# Generated by Django 4.1.1 on 2022-09-28 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recordatorio', '0001_initial'),
        ('Destinatario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatario',
            name='idRecordatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recordatorio.recordatorio', verbose_name='Id Recordatorio'),
        ),
    ]
