# Generated by Django 4.1.1 on 2022-09-23 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Secretaria', '0002_alter_secretaria_telefono'),
        ('Cliente', '0003_remove_cliente_id_alter_cliente_dpicliente'),
        ('Abogada', '0003_remove_abogada_id_alter_abogada_colegiado'),
    
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(help_text='Ingresa el Motivo', max_length=15, verbose_name='Motivo')),
                ('fechaInicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Inicio')),
                ('fechaFin', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Fin')),
                ('dpiSecre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Secretaria.secretaria')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
                ('idColegiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abogada.abogada')),
                
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'consulta',
            },
        ),
    ]
