# Generated by Django 4.1.1 on 2022-09-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fechaFin',
            field=models.DateTimeField(auto_now_add=True, db_column='Fecha Fin', verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fechaInicio',
            field=models.DateTimeField(auto_now_add=True, db_column='Fecha Inicio', verbose_name='Fecha Inicio'),
        ),
    ]
