# Generated by Django 4.1.1 on 2022-09-28 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0005_alter_cliente_genero'),
        ('Abogada', '0003_remove_abogada_id_alter_abogada_colegiado'),
        ('Secretaria', '0002_alter_secretaria_telefono'),
        ('Consulta', '0003_alter_consulta_fechafin_alter_consulta_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='dpiSecre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Secretaria.secretaria', verbose_name='DPI Secretaria'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente', verbose_name='DPI Cliente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='idColegiado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abogada.abogada', verbose_name='ID Colegiado'),
        ),
    ]
