# Generated by Django 4.1.1 on 2022-10-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consulta', '0004_alter_consulta_dpisecre_alter_consulta_idcliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='fechaFin',
            new_name='faFin',
        ),
    ]
