# Generated by Django 4.1.1 on 2022-10-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consulta', '0005_rename_fechafin_consulta_fafin'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('I', 'Iniciado'), ('P', 'En proceso'), ('S', 'En pausa'), ('F', 'Finalizado'), ('E', 'Entregado'), ('C', 'Cancelado')], default=1, help_text='Seleccione el estado', max_length=1, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
