# Generated by Django 4.1.1 on 2022-10-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consulta', '0006_consulta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='motivo',
            field=models.CharField(help_text='Ingresa el Motivo', max_length=200, verbose_name='Motivo'),
        ),
    ]
