# Generated by Django 4.1.1 on 2022-10-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consulta', '0008_alter_consulta_idcliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='faFin',
        ),
    ]
