# Generated by Django 4.1.1 on 2022-10-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consulta', '0009_remove_consulta_fafin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='dpiSecre',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='idColegiado',
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo_persona',
            field=models.CharField(choices=[('I', 'Iniciado'), ('P', 'En proceso'), ('S', 'En pausa'), ('F', 'Finalizado'), ('E', 'Entregado'), ('C', 'Cancelado')], default=1, help_text='Seleccione el tipo de Persona', max_length=1, verbose_name='Tipo de Persona'),
            preserve_default=False,
        ),
    ]
