# Generated by Django 4.1.1 on 2022-10-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consulta', '0010_remove_consulta_dpisecre_remove_consulta_idcolegiado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='tipo_persona',
            field=models.CharField(choices=[('S', 'Secretaria'), ('A', 'Abogada')], help_text='Seleccione el tipo de Persona', max_length=1, verbose_name='Tipo de Persona'),
        ),
    ]
