# Generated by Django 4.1.1 on 2022-09-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese Nombre', max_length=30, verbose_name='Nombre')),
                ('apelllido', models.CharField(help_text='Ingrese Apellido', max_length=30, verbose_name='Apellido')),
                ('telefono', models.BigIntegerField(blank=True, help_text='Ingrese Número de Teléfono', null=True, verbose_name='Teléfono')),
                ('dpicliente', models.CharField(help_text='Ingresa DPI', max_length=20, verbose_name='DPI de Cliente')),
                ('direccion', models.CharField(help_text='Ingresar Dirección', max_length=50, verbose_name='Dirección')),
                ('genero', models.BooleanField(help_text='Ingresar Dirección', verbose_name='Dirección')),
                ('nit', models.CharField(help_text='Ingrese Nit', max_length=15, verbose_name='Nit')),
                ('estadocivil', models.CharField(help_text='Ingrese Estado Civil', max_length=10, verbose_name='Estado Civil')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
    ]
