# Generated by Django 4.1.1 on 2022-09-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.BooleanField(choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Ingrese su genero', max_length=1, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text='Ingrese Número de Teléfono', max_length=20, verbose_name='Teléfono'),
        ),
    ]
