# Generated by Django 4.1.1 on 2022-09-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_alter_cliente_genero_alter_cliente_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dpicliente',
            field=models.CharField(help_text='Ingresa DPI', max_length=20, primary_key=True, serialize=False, verbose_name='DPI de Cliente'),
        ),
    ]
