# Generated by Django 4.1.1 on 2022-09-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_remove_cliente_id_alter_cliente_dpicliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.BooleanField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', help_text='Ingrese su genero', max_length=1, verbose_name='Genero'),
        ),
    ]
