# Generated by Django 4.1.1 on 2022-09-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
