# Generated by Django 4.1.1 on 2022-09-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abogada', '0002_alter_abogada_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abogada',
            name='id',
        ),
        migrations.AlterField(
            model_name='abogada',
            name='colegiado',
            field=models.CharField(help_text='Ingresa Colegiado', max_length=20, primary_key=True, serialize=False, verbose_name='Colegiado'),
        ),
    ]
