# Generated by Django 4.1.1 on 2022-09-23 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Consulta', '0003_alter_consulta_fechafin_alter_consulta_fechainicio'),
        ('Tipo_Doc_Notarial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento_Notarial',
            fields=[
                ('idDocumento_Notarial', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField(blank=True, null=True)),
                ('idConsulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consulta.consulta')),
                ('idTipo_Doc_Notarial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tipo_Doc_Notarial.tipo_doc_notarial')),
            ],
            options={
                'verbose_name': 'Documento Notarial',
                'verbose_name_plural': 'Documentos Notariales',
                'db_table': 'documento notarial',
            },
        ),
    ]
