# Generated by Django 4.1.1 on 2022-09-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documento_Notarial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento_notarial',
            name='estado',
            field=models.CharField(choices=[('I', 'Iniciado'), ('P', 'En proceso'), ('S', 'En pausa'), ('F', 'Finalizado'), ('E', 'Entregado'), ('C', 'Cancelado')], default=1, help_text='Seleccione el estado', max_length=1, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
