# Generated by Django 4.1.1 on 2022-10-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documento_Notarial', '0002_documento_notarial_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento_notarial',
            name='estado',
        ),
    ]
