# Generated by Django 4.1.1 on 2022-10-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consulta', '0008_alter_consulta_idcliente'),
        ('Tipo_Doc_Notarial', '0002_alter_tipo_doc_notarial_tipo_documento'),
        ('Documento_Notarial', '0003_remove_documento_notarial_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento_notarial',
            name='idConsulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consulta.consulta', verbose_name='Consulta'),
        ),
        migrations.AlterField(
            model_name='documento_notarial',
            name='idTipo_Doc_Notarial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tipo_Doc_Notarial.tipo_doc_notarial', verbose_name='Tipo de Documento Notarial'),
        ),
    ]
