# Generated by Django 4.1.1 on 2022-10-08 03:18

from django.db import migrations, models
import sistema.valida


class Migration(migrations.Migration):

    dependencies = [
        ('Documento_Notarial', '0004_alter_documento_notarial_idconsulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento_notarial',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/notariales', validators=[sistema.valida.validate_file_extension]),
        ),
    ]
