# Generated by Django 4.1.1 on 2022-09-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Doc_Notarial',
            fields=[
                ('idTipo_Doc_Notarial', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(help_text='Ingresa el Tipo', max_length=15, verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'db_table': 'tipo_de_documento',
            },
        ),
    ]
