# Generated by Django 4.1.1 on 2022-10-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tipo_Doc_Notarial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_doc_notarial',
            name='tipo_documento',
            field=models.CharField(help_text='Ingresa el Tipo', max_length=200, verbose_name='Tipo de Documento'),
        ),
    ]
